<p>well, click something...</p>
<p>the forms below are not yet available :P</p>
<table>
    <tr>
        <td>
            Artist name:
        </td>
        <td>
            <input id="artist" type="text" value="">
        </td>
        <td>
            <input type="button" value="Go"/>
        </td>
    </tr>
    <tr>
        <td>
            Song/Track name:
        </td>
        <td>
            <input id="track" type="text">
        </td>
        <td>
            <input type="button" value="Go"/>
        </td>
    </tr>
</div>
<script type="text/javascript">                                         
$(document).ready(function() {
// do stuff when DOM is ready
    $("#artist").autocomplete(url+"/query/getartistsbyline/"+$("#artist").val());
    
    $("#track").autocomplete(url+"/query/gettracksbyline/"+$("#track").val());
});                             
</script>  
