<p>well, click something...</p>
<table>
    <tr>
        <td>
            Artist name:
        </td>
        <form method="get" action="index/byalpha">
        <td>
            <input id="artist" name="q" type="text" value="">
        </td>
        <td>
            <input type="submit" value="Go"/>
        </td>
        </form>
        <td>
            Song/Track name (not working yet):
        </td>
        <td>
            <input id="track" type="text">
        </td>
        <td>
            <input type="button" value="Go"/>
        </td>
    </tr>
</table>
<p>
    To do:
    <ol>
        <li>Display the lyrics</li>
        <li>Make the Song/Track search work</li>
    </ol>
</p>
<script type="text/javascript">                                         
$(document).ready(function() {
// do stuff when DOM is ready
    $("#artist").autocomplete(url+"/query/getartistsbyline/"+$("#artist").val());
    
    $("#track").autocomplete(url+"/query/gettracksbyline/"+$("#track").val());
});                             
</script>  
