<p>well, click something...</p>
<p>the forms below are not yet available :P</p>
<table>
    <tr>
        <td>
            Type an artist name:
            <input id="artist" type="text" value="test">
        </td>
        <td>
            OR Type a song/track name:
            <input type="text">
        </td>
    </tr>
</div>
<script type="text/javascript">                                         
$(document).ready(function() {
// do stuff when DOM is ready
    var data = "Core Selectors Attributes Traversing Manipulation CSS Events Effects Ajax Utilities".split(" ");
    $("#artist").autocomplete(data);
    //alert($("#artist").val());
});                             
</script>  
